# Generated by AAA COC AI MARCO Screenshot-to-Code Engine
def auto_raid(engine):
    engine.zap_targets([[750, 480], [1170, 480]])
    engine.funnel_heroes(king=(450, 850), queen=(1450, 850))
    engine.spread_dragons(start=(600, 820), end=(1350, 820))
    engine.drop_warden(960, 850)
    engine.cast_rage(960, 540)
